find_package(Python COMPONENTS Interpreter Development.Module REQUIRED)

execute_process(
    COMMAND 
        ${Python_EXECUTABLE} -c "import pyhmmer; print(pyhmmer.__path__[0], end='.libs')"
    OUTPUT_VARIABLE 
        PYHMMER_LIBS_DIR
)

message(STATUS "Found PyHMMER: ${PYHMMER_LIBS_DIR}")

set(PyHMMER_FOUND true)
cmake_path(APPEND PYHMMER_LIBS_DIR "include" "libeasel" OUTPUT_VARIABLE _PYHMMER_EASEL_INCLUDE)
cmake_path(APPEND PYHMMER_LIBS_DIR "include" "libhmmer" OUTPUT_VARIABLE _PYHMMER_HMMER_INCLUDE)

cmake_path(APPEND PYHMMER_LIBS_DIR "liblibeasel${CMAKE_SHARED_LIBRARY_SUFFIX}" OUTPUT_VARIABLE _PYHMMER_EASEL_LIB)
cmake_path(APPEND PYHMMER_LIBS_DIR "liblibhmmer${CMAKE_SHARED_LIBRARY_SUFFIX}" OUTPUT_VARIABLE _PYHMMER_HMMER_LIB)

set(PyHMMER_INCLUDE_DIRS "${_PYHMMER_EASEL_INCLUDE}" "${_PYHMMER_HMMER_INCLUDE}")
set(PyHMMER_LIBRARIES    "${_PYHMMER_EASEL_LIB}" "${_PYHMMER_HMMER_LIB}")
